### ISSUE TITLE
Question related to the requirement of S3 compatible bucket for backup

### ISSUE THREAD

**Issue by ipochi** [openebs/velero-plugin#2]
Hi @mynktl 

I have a quick question based on the slides I read from here [ especially slide-8 ]
https://www.slideshare.net/OpenEBS/thoughts-on-heptios-ark-contributors-meet-21st-sept-2018

```Backup/Restore via OpenEBS ARK Plugin 8 - Create a OpenEBS ARK Plugin that will implement the Block-Store API exposed by ARK - Backup Operation - ARK will invoke the Plugin-Snapshot (Backup) method. - Plugin: will call maya-apiserver backup api on a given volume - Maya-apiserver backup will call volumes (jiva/cstor) backup api - (jiva/cstor) volume controller will take a snapshot, and pass the request to one of the replica’s to push snapshot data to remote backup location (say S3 compatible -- as passed via the ark plugin or a custom backup location on mayaonline or may be a nfs server that openebs supports ). The code to actually push the data to backup location can make use of restic. We are putting it at the jiva/cstor for getting access to snapshot/incr snapshot data. - Restore Operation - ARK will invoke the Plugin-VolumeFromSnapshot (Restore) method - Plugin will invoke maya-apiserver to create a new PV/PVC and restore the data from backup. - ARK will launch the application with the PV/PVC.```

Is this the same plugin mentioned in the slide and regarding the possibility of using nfs location for backup rather than s3 compatible object storage.

Little bit confused as Velero mentions s3 compatible object storage as a mandatory requirement for 
backup.

How different it is to use Ark with Restic to backup openebs cstor block volumes than use this plugin ?
Both would serve the same purpose I presume.

**Comment by mynktl** [comment]
Hi @ipochi 
Thanks for showing interest in ark plugin.

>Is this the same plugin mentioned in the slide and regarding the possibility of using nfs location for backup rather than s3 compatible object storage.

Yes. This is the same plugin mentioned in that slide. As of now, this plugin is in the development stage.
For volume snapshot, you can use NFS storage location. To store the backup metadata, you need to use the s3 compatible object storage.

>Little bit confused as Velero mentions s3 compatible object storage as a mandatory requirement for
backup.

To store the backup metadata, you need to use s3 compatible object storage since the backup is handled through ARK server. You may store the volume snapshot to the different storage location(locations supported by this plugin) other than s3.

>How different it is to use Ark with Restic to backup openebs cstor block volumes than use this plugin ?
Both would serve the same purpose I presume.

Yes. I agree with you. Both will serve the same purpose.
Difference is :
1. Restic provides file-level backup/restore and **this plugin provides block-level backup/restore**.
Block level backup/restore consumes **less storage** and also **less network bandwidth**.

######  Thank You.

**Comment by mynktl** [comment]
Hi @ipochi 

Yes, Restic will take a file-level backup regardless of the storage engine type.

In the file-level backup, backup is performed by copying each file from volume mount-path to a remote storage location. You can refer to this [link](https://www.linkedin.com/pulse/file-level-backup-vs-block-mike-wang) for more information on file-level backup.

Regarding your last question..
You can check the list of supported backup storage provider [here](https://github.com/heptio/velero/blob/master/docs/support-matrix.md#backup-storage-providers). A plugin is required if the storage engine has its own snapshot/backup feature(other than restic-way).

**Comment by mynktl** [comment]
Hi @ipochi  
We have released our velero-plugin!! which supports AWS and GCP backup storage location as of now.
